language: node_js
node_js:
- 7.7.1
after_script:
-scp -o StrictHostKeyChecking=no app.js root@119.29.6.254:/usr/local/nginx/html
before_install:
- openssl aes-256-cbc -K $encrypted_92c2e03cabf7_key -iv $encrypted_92c2e03cabf7_iv
  -in git_rsa.enc -out ~/.ssh/git_rsa -d
# 改变文件权限
  - chmod 600 ~/.ssh/git_rsa

  # 配置 ssh
   - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
     - cp .travis/ssh_config ~/.ssh/config
