language: node_js
node_js:
- 7.7.1
before_install:
- openssl aes-256-cbc -K $encrypted_92c2e03cabf7_key -iv $encrypted_92c2e03cabf7_iv
  -in .travis/git_rsa.enc -out ~/.ssh/git_rsa -d
install: npm install
script: npm run test
after_script:
- scp -o StrictHostKeyChecking=no app.js root@119.29.6.254:/usr/local/nginx/html/testTravis
